---
title: "Schedule"
author: "Davi Moreira"
date-modified: "last-modified"
date: "2024-01-18"
date-format: "MMM D, YYYY"
# listing:
#   - id: schedule
#     contents:
#       - topics/topic-*.qmd
#     type: table
#     fields: [week, title, subtitle, date]
#     field-display-names:
#       week: "Week"
#       title: "Topic"
#       description: "Dates"
#       subtitle: "Description"
#     date-format: "MMMM DD, YYYY to MMMM DD, YYYY"
#     sort: [filename]
#     sort-ui: false
#     filter-ui: false
 #tbl-colwidths: [5,20,50,25]
editor: visual
---


| Week    | Topic    | Title                                      | Date    |
|:--------|:-------------------|:-------------------------------------------|:--------|
| Week 01 | [Topic 01](./topics-pages/page-topic-01.qmd) | Introduction, Syllabus and Set up   | Jan 18  |
| Week 02 | [Topic 01](./topics-pages/page-topic-01.qmd) | Introduction, Syllabus and Set up   | Jan 23  |
| Week 02 | [Topic 02](./topics-pages/page-topic-02.qmd)  | Computational Literacy, Command Line, and Version Control                            | Jan 25  |
| Week 03 | [Topic 02](./topics-pages/page-topic-02.qmd)  | Computational Literacy, Command Line, and Version Control | Jan 30  |
| Week 03 | [Topic 02](./topics-pages/page-topic-02.qmd)  | Computational Literacy, Command Line, and Version Control                            | Feb 1   |
| Week 04 | [Topic 02](./topics-pages/page-topic-02.qmd)  | Computational Literacy, Command Line, and Version Control                        | Feb 6   |
| Week 04 | [Topic 02](./topics-pages/page-topic-02.qmd)  | Computational Literacy, Command Line, and Version Control                        | Feb 8   |
| Week 05 | [Topic 02](./topics-pages/page-topic-02.qmd)  | Computational Literacy, Command Line, and Version Control          | Feb 13  |
| Week 05 | [Topic 02](./topics-pages/page-topic-02.qmd)  | Computational Literacy, Command Line, and Version Control          | Feb 15  |
| Week 06 | [Topic 03](./topics-pages/page-topic-04.qmd)  | Python essentials  | Feb 20  |
| Week 06 | [Topic 03](./topics-pages/page-topic-04.qmd)  | Python essentials  | Feb 22  |
| Week 07 | [Topic 03](./topics-pages/page-topic-04.qmd)  | Python essentials  | Feb 27  |
| Week 07 | [Topic 03](./topics-pages/page-topic-04.qmd)  | Python essentials  | Feb 29  |
| Week 08 | [Topic 03](./topics-pages/page-topic-04.qmd)  | Python essentials  | Mar 5   |
| Week 08 | [Topic 03](./topics-pages/page-topic-04.qmd)  | Python essentials  | Mar 7   |
| Week 09 | -        | Spring Break (no classes, no office hours) | Mar 12  |
| Week 09 | -        | Spring Break (no classes, no office hours) | Mar 14  |
| Week 10 | [Topic 04](./topics-pages/page-topic-04.qmd)  | Algorithms and Data Structures | Mar 19  |
| Week 10 | [Topic 04](./topics-pages/page-topic-04.qmd)  | Algorithms and Data Structures | Mar 21  |
| Week 11 | [Topic 04](./topics-pages/page-topic-04.qmd)  | Algorithms and Data Structures | Mar 26  |
| Week 11 | [Topic 04](./topics-pages/page-topic-04.qmd)  | Algorithms and Data Structures | Mar 28  |
| Week 12 | [Topic 05](./topics-pages/page-topic-05.qmd)  | API Interactions and Web Scraping | Apr 2 |
| Week 12 | [Topic 06](./topics-pages/page-topic-06.qmd)  | SQL vs NoSQL  | Apr 4   |
| Week 13 | [Topic 07](./topics-pages/page-topic-07.qmd)  | SQL Operations and Operators             | Apr 9   |
| Week 13 | [Topic 08](./topics-pages/page-topic-08.qmd)  | Database Design, Structures and Management             | Apr 11  |
| Week 14 | [Topic 09](./topics-pages/page-topic-09.qmd)  | Create, Populate and Manipulate databases             | Apr 16  |
| Week 14 | [Topic 10](./topics-pages/page-topic-10.qmd)  | Cloud Computing and Data Bases             | Apr 18  |
| Week 15 | [Topic 11](./topics-pages/page-topic-11.qmd)  | Final Project                              | Apr 23  |
| Week 15 | [Topic 11](./topics-pages/page-topic-11.qmd)  | Final Project                              | Apr 25  |