---
title: "Topic 02"
subtitle: "Version Control"
description: ""
author: "Davi Moreira"
date: "2024-01-23"
#listing:
  # - id: slides
  #   contents:
  #     - ../slides/topic-01/*.qmd
  #   type: table
  #   fields: [title, date]
  #   date-format: "ddd, MMM DD"
  #   field-display-names:
  #     title: "Topic"
  #     date: "Date"
  #   sort: [filename]
  #   sort-ui: false
  #   filter-ui: false
  # - id: assignments
  #   contents:
  #     - ../hw/w1-*.qmd
  #     - ../labs/w1-*.qmd
  #   type: table
  #   fields: [categories, title, date]
  #   date-format: "ddd, MMM DD"
  #   field-display-names:
  #     categories: "Assignment"
  #     title: "Title"
  #     date: "Due"
  #   sort: [date]
  #   sort-ui: false
  #   filter-ui: false
tbl-colwidths: [10,50,40]
---

# Lecture Notes

-   Computational Literacy: [html](/lecture_notes/topic-02/_version_control_git.html), <a href="/lecture_notes/topic-02/_version_control_git.ipynb" download> notebook </a>

-   Basics of Command Line: [html](/lecture_notes/topic-01/_basics_of_cmd.html), <a href="/lecture_notes/topic-01/_basics_of_cmd.ipynb" download> notebook </a>

-   Version Control: [html](/lecture_notes/topic-02/_version_control_git.html), <a href="/lecture_notes/topic-02/_version_control_git.ipynb" download> notebook </a>

# Slides

-   [Computational Literacy, Command Line, and Version Control:](/slides/topic-2.html)

# Practice Exercises

-   XXXX

-   XXXX[Solutions](/solutions_html/_topic_02_solution.html)XXXX

# Readings

***Required Readings***

-   [The Plain Person's Guide to Plain Text Social Science](http://plain-text.co/) - Healy, Kieran

    -   Ch. 1: Introduction;

    -   Ch. 2: Keep a Record;

    -   Ch. 3: Write and Edit;

    -   Ch. 4: Reproduce Work.

-   [Pro Git](https://git-scm.com/book/en/v2) - Chacon & Straub

    -   [Ch. 1: Getting Started](https://git-scm.com/book/en/v2/Getting-Started-About-Version-Control); Read 1.1 - 1.3

    -   [Ch. 2: Git Basics](https://git-scm.com/book/en/v2/Git-Basics-Getting-a-Git-Repository); Only read 2.1 - 2.5

    -   [Ch. 3: Git Branching](https://git-scm.com/book/en/v2/Git-Branching-Branches-in-a-Nutshell)

***Additional Resources and Suggested Materials***

-   More on Git/Github in Pro Git:
    -   [Read 1.4 - 1.7](https://git-scm.com/book/en/v2/Getting-Started-The-Command-Line) for help on installation and commandline

    -   Read [Ch. 6](https://git-scm.com/book/en/v2/GitHub-Account-Setup-and-Configuration) for more information regarding Git + Github.
-   [Ch. 13 Detect Git from RStudio -Happy Git with R](https://happygitwithr.com/rstudio-see-git.html) - Bryan, Jenny & Jim Hester
